.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. dorkcoin_qt test_dorkcoin_qt
clean: FORCE
	$(MAKE) -C .. dorkcoin_qt_clean test_dorkcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_dorkcoin_qt_check
dorkcoin-qt dorkcoin-qt.exe: FORCE
	 $(MAKE) -C .. dorkcoin_qt
